Trying to detect other array suites for comparison in configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -52,6 +52,82 @@ else
             echo "WARNING: Omitting non-exising fortran compiler ${FC}."
             grep -v "FC=${FC}" ${CXXMKINC} | grep -v "FFLAGS=" > config.mk
         fi
+        # detect installation of BLITZ (only needed for benchmarks)
+        echo -e "#\n# Comparison test settings\n#" >> config.mk
+        echo -n "MORECPPFLAGSOPT=-DNDEBUG" >> config.mk
+        #########################################################
+        headerfile="blitz/array.h"
+        echo -n "Detecting $headerfile... " 
+        tmpfile=$(mktemp --suffix .cc)
+        cat > $tmpfile <<-EOF
+	#include "$headerfile"
+	int main(){return 0;}
+EOF
+        if ! $CXX $tmpfile &> /dev/null; then 
+            echo "not found"
+            echo -n " -DNOBLITZ" >> config.mk
+        else
+            echo "found"
+        fi
+        #########################################################
+        headerfile="boost/multi_array.hpp"
+        echo -n "Detecting $headerfile... " 
+        cat > $tmpfile <<-EOF
+	#include "$headerfile"
+	int main(){return 0;}
+EOF
+        if ! $CXX $tmpfile &> /dev/null; then 
+            echo "not found"
+            echo -n " -DNOBOOST" >> config.mk
+        else
+            echo "found"
+            echo -n " -DBOOST_DISABLE_ASSERTS" >> config.mk
+        fi
+        #########################################################
+        headerfile="eigen3/Eigen/Dense"
+        echo -n "Detecting $headerfile... " 
+        cat > $tmpfile <<-EOF
+	#include "$headerfile"
+	int main(){return 0;}
+EOF
+        if ! $CXX $tmpfile &> /dev/null; then 
+            echo "not found"
+            echo -n " -DNOEIGEN3" >> config.mk
+        else
+            echo "found"
+            echo -n " -DEIGEN_NO_DEBUG" >> config.mk
+        fi
+        #########################################################
+        modulename="ARMADILLO"
+        headerfile="armadillo"
+        echo -n "Detecting $headerfile... " 
+        incdir=$(env | grep ${modulename}_I | awk -F= '{print $1}')
+        libdir=$(env | grep ${modulename}_L | awk -F= '{print $1}')
+        if ! [ "$libdir" ]; then libdir=. ; fi
+        cat > $tmpfile <<-EOF
+	#include "$headerfile"
+	int main(){return 0;}
+EOF
+        if [ "$incdir" ]; then
+            if ! $CXX -I"$envdir" -L"$libdir" $tmpfile &> /dev/null; then 
+                echo "not found"
+                echo -n " -DNOARMADILLO" >> config.mk
+            else
+                accincdir="$accincdir -I$$$incdir"
+                acclibdir="$acclibdir -I$$$libdir"
+                echo "found"
+            fi
+        else
+            if ! $CXX $tmpfile &> /dev/null; then 
+                echo "not found"
+                echo -n " -DNOARMADILLO" >> config.mk
+            else
+                echo "found"
+            fi
+        fi
+        #########################################################
+        echo >> config.mk
+        
         # add prefix to the makefile include file
         echo -e "#\n# Default installation directory\n#\nPREFIX?=${prefix}" >> config.mk
         # print what to do next
